name: Build and release

on:
  workflow_dispatch:
  push:
    tags:
      - v*
  pull_request:
    tags:
      - v*

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - name: Prepaire
        run: chmod +x gradlew
      - name: Build
        run: ./gradlew build

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: app/build/outputs/apk/release/app-release.apk
